#!/usr/bin/env python3
"""Regenerate metadata-only fixtures: generate.py /absolute/path/to/alr NEW_DIR.

Requires ALIRE 2.1.1. This is a maintainer utility, never invoked by Go tests or
Trivy. No community index, Ada compiler, package actions, or network is needed.
"""

import os
from pathlib import Path
import subprocess
import sys
import tempfile


def manifest(name, version="1.0.0", dependencies=None, pins=None):
    text = (
        f'name = "{name}"\nversion = "{version}"\n'
        'description = "Synthetic Trivy inventory fixture"\n'
        'licenses = "Apache-2.0"\nproject-files = []\n'
    )
    if dependencies:
        text += "\n[[depends-on]]\n"
        text += "".join(f'{name} = "{constraint}"\n' for name, constraint in dependencies.items())
    if pins:
        text += "\n[[pins]]\n" + pins + "\n"
    return text


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def main():
    alr = Path(sys.argv[1]).resolve(strict=True)
    output = Path(sys.argv[2]).resolve()
    if output.exists():
        raise SystemExit("Output must be a new directory")
    if subprocess.check_output([alr, "--version"], text=True).strip() != "alr 2.1.1":
        raise SystemExit("Requires ALIRE 2.1.1")
    output.mkdir(parents=True)
    with tempfile.TemporaryDirectory(prefix="trivy-alire-fixtures-") as tmp:
        work = Path(tmp)
        env = dict(os.environ, ALIRE_SETTINGS_DIR=str(work / "settings"),
                   XDG_DATA_HOME=str(work / "data"), XDG_CACHE_HOME=str(work / "cache"))

        def run(*args):
            subprocess.run([alr, "-n", *args], env=env, check=True,
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

        for key, value in {
            "index.auto_community": "false", "index.auto_update": "0",
            "toolchain.assistant": "false", "distribution.disable_detection": "true",
            "dependencies.shared": "false", "cache.dir": str(work / "cache"),
        }.items():
            run("settings", "--global", "--set", key, value)
        write(work / "index/index.toml", 'version = "1.4"\n')
        for name, version, dependencies in [
            ("leaf_dep", "2.0.0", None),
            ("direct_dep", "1.0.0", {"leaf_dep": "^2.0.0"}),
            ("right_dep", "1.0.0", {"leaf_dep": "^2.0.0"}),
        ]:
            text = manifest(name, version, dependencies)
            write(work / f"sources/{name}/alire.toml", text)
            # Insert index-only metadata before the first table.
            text = text.replace('project-files = []\n',
                                'project-files = []\nmaintainers = ["maintainer@example.invalid"]\n'
                                'maintainers-logins = ["trivy-fixture"]\n')
            text += f'\n[origin]\nurl = "file:../../../sources/{name}"\n'
            write(work / f"index/{name[:2]}/{name}/{name}-{version}.toml", text)
        run("index", "--add", str(work / "index"), "--name", "fixtures")
        cases = {
            "resolved": manifest("inventory_app", dependencies={"direct_dep": "^1.0.0"}),
            "diamond": manifest("diamond_app", dependencies={"direct_dep": "^1.0.0", "right_dep": "^1.0.0"}),
            "empty": manifest("empty_app"),
            "linked": manifest("linked_app", dependencies={"direct_dep": "^1.0.0"},
                               pins='direct_dep = { path = "../local_dep" }'),
            "version-pin": manifest("pinned_app", dependencies={"direct_dep": "^1.0.0"},
                                    pins='direct_dep = { version = "1.0.0" }'),
            "missed": manifest("missing_app", dependencies={"missing_dep": "^9.0.0"}),
            "unresolved": manifest("unresolved_app", dependencies={"missing_dep": "^9.0.0"}),
        }
        # Deliberately outside the requested range: local overrides ignore it.
        local = manifest("direct_dep", "3.1.0", {"leaf_dep": "^2.0.0"})
        write(work / "projects/local_dep/alire.toml", local)
        for case, text in cases.items():
            project = work / "projects" / case
            write(project / "alire.toml", text)
            if case != "unresolved":
                run("-C", str(project), "with", "--solve")
            members = {f"{case}/alire.toml": text}
            lock = project / "alire/alire.lock"
            if lock.exists():
                # Source locators are metadata, never read by Trivy. Normalize
                # only the temporary generation prefix for reproducible files.
                content = lock.read_text().replace(str(work), "<FIXTURE_DIR>").rstrip() + "\n"
                write(output / f"{case}.lock", content)
                members[f"{case}/alire/alire.lock"] = content
            if case == "linked":
                members["local_dep/alire.toml"] = local
            archive = "Generated by ALIRE 2.1.1 with generate.py; Apache-2.0 synthetic metadata.\n"
            for name, data in sorted(members.items()):
                archive += f"-- {name} --\n{data.rstrip()}\n"
            write(output / f"{case}.txtar", archive)


if __name__ == "__main__":
    main()
